basic:
  split: 'val'         # dataset split, val/test
  has_velo: True       # whether detector has velo info
  LiDAR_interval: 0.5  # the interval between two adjacent frames of the LiDAR scan, NuScenes: 2HZ
  CLASS_NUM: 7         # number of tracking category, NuScenes: 7

  # CLASS_LABEL: {'bicycle': 0, 
  #               'bus': 1, 
  #               'car': 2, 
  #               'motorcycle': 3, 
  #               'pedestrian': 4, 
  #               'trailer': 5, 
  #               'truck': 6}

preprocessing:
  SF_thre: {0: 0.01, 3: 0.01, 1: 0.01, 2: 0.01, 5: 0.01, 6: 0.01, 4: 0.1} # default {0: 0.14, 3: 0.16, 1: 0, 2: 0.16, 5: 0.1, 6: 0, 4: 0.16}
  NMS_thre: 0 # default 0.08
  NMS_type: blend_nms  # blend_nms, no_blend_nms, blend_soft_nms
  NMS_metric: iou_bev  # iou_bev, iou_3d, giou_bev, giou_3d, d_eucl

association:
  category_metrics: {1: 'giou_bev', 0: 'giou_3d', 2: 'giou_bev', 3: 'giou_3d', 4: 'giou_3d', 5: 'giou_3d', 6: 'giou_3d'} # default {1: 'giou_bev', 0: 'giou_3d', 2: 'giou_3d', 3: 'giou_3d', 4: 'giou_3d', 5: 'giou_3d', 6: 'giou_3d'}
  second_metric: 'giou_bev'
  two_stage: True # default: True  # Whether to use two-stage data association
  first_thre: {1: 1.34, 0: 1.55, 2: 1.31, 3: 1.44, 4: 1.69, 5: 1.25, 6: 1.21} # default {1: 1.34, 0: 1.55, 2: 1.31, 3: 1.44, 4: 1.69, 5: 1.25, 6: 1.21}  # category-specific one-stage thresholds
  second_thre: {0: 1.0}  # two-stage thresholds
  algorithm : 'Hungarian'  # default Hungarian # Greedy, Hungarian, Mutual Nearest Neighbor(MNN)

motion_model:
  # two kalman filter, LinearKalmanFilter, ExtendKalmanFilter
  # filter: {1: 'ExtendKalmanFilter', 0: 'ExtendKalmanFilter', 2: 'ExtendKalmanFilter', 3: 'ExtendKalmanFilter', 4: 'ExtendKalmanFilter', 5: 'ExtendKalmanFilter', 6: 'ExtendKalmanFilter'}
  # five motion model, Linear Model: CV, CA, Non-Linear: CTRA, CTRV, BICYCLE
  # note the consistency of the linear relationship between the model and the filter
  # model: {1: 'CTRA', 0: 'BICYCLE', 2: 'CTRA', 3: 'BICYCLE', 4: 'CTRA', 5: 'CTRA', 6: 'CTRA'}
  filter: {1: 'ExtendKalmanFilter', 0: 'ExtendKalmanFilter', 2: 'LinearKalmanFilter', 3: 'ExtendKalmanFilter', 4: 'ExtendKalmanFilter', 5: 'LinearKalmanFilter', 6: 'ExtendKalmanFilter'}
  model: {1: 'CTRV', 0: 'CTRV', 2: 'CV', 3: 'CTRV', 4: 'CTRV', 5: 'CV', 6: 'CTRV'} # default {1: 'CTRA', 0: 'BICYCLE', 2: 'CTRA', 3: 'BICYCLE', 4: 'CTRA', 5: 'CA', 6: 'CTRA'}

life_cycle:
  max_age: {1: 10, 0: 10, 2: 15, 3: 20, 4: 10, 5: 10, 6: 20}
  min_hit: {1: 1, 0: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}
  decay_rate: {0: 0.05, 3: 0.1, 1: 0.3, 2: 0.2, 5: 0.15, 6: 0.25, 4: 0.15}

output:
  punish_num: 1         # The maximum number of predicted frames to write to the output file
  post_nms: False       # whether to use post-nms, this feature is used to reduce FP prediction
  NMS_thre: 0.08
  NMS_type: blend_nms   # blend_nms, no_blend_nms, blend_soft_nms
  NMS_metric: iou_bev   # iou_bev, iou_3d, giou_bev, giou_3d, d_eucl

debug:
  is_debug: False # default true # Whether to debug the code

